server:
  port: 8671
spring:
  application:
    name: eurekaserver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka
    fetch-registry: false # ?????????eureka server??????
    register-with-eureka: false # ????????????????
