spring:
  application:
    name: gateway
  cloud:
    consul:
      host: localhost
      port: 8500
    gateway:
      routes:
        - id: user_route
          uri: lb://users
          # uri: http://localhost:9999/
          predicates:
            - Path=/user/**
            - After=2022-07-21T11:39:33.993+08:00[Asia/Shanghai]

        - id: product_route
          uri: lb://products
          # uri: http://localhost:9998/
          predicates:
            - Path=/product/**
          filters:
            - AddRequestParameter=id, 34
server:
  port: 8989

management:
  endpoints:
    web:
      exposure:
        include: "*"
